name: Build zerotier

on: 
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: build
      run: |
          git clone https://github.com/soulherats/Entware /opt/rt-n56u
          cd /opt/rt-n56u
          make package/symlinks
          cp -v configs/mipsel-3.4.config .config
    - name: build after
      run: |  
          cd /opt/rt-n56u
          make -j$(nproc) tools/install V=s
          make -j$(nproc) toolchain/install V=s
          make -j$(nproc) target/compile
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: 1.10.1
      run: |
          git clone https://github.com/zerotier/ZeroTierOne
          cd ZeroTierOne
          git checkout $DEBIAN_FRONTEND
          sed -i '243,247d' osdep/LinuxEthernetTap.cpp
          git diff > home.patch
          cat home.patch
    - uses: actions/checkout@v2
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
    - name: build zerotier
      run: | 
          cd /opt/rt-n56u
          mkdir /opt/images
          make package/zerotier/compile
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images      
