name: Build zerotier

on: 
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: build
      run: |
          git clone https://github.com/soulherats/Entware /opt/rt-n56u
          cd /opt/rt-n56u
          make package/symlinks
          cp -v configs/mipsel-3.4.config .config
    - name: Set up Python 2x
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '2.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
    - name: build after
      run: |  
          cd /opt/rt-n56u
          make -j$(nproc) tools/install V=s
          make -j$(nproc) toolchain/install V=s
          make -j$(nproc) target/compile
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: 1.10.1
      run: |
          cd /opt
          git clone https://github.com/zerotier/ZeroTierOne
          cd ZeroTierOne
          git checkout $DEBIAN_FRONTEND
          sed -i '273,288d' osdep/LinuxEthernetTap.cpp
          git diff > home.patch
          cp home.patch /opt/rt-n56u/feeds/packages/net/zerotier/patches
          cat home.patch
    - name: build zerotier
      run: | 
          cd /opt/rt-n56u
          mkdir /opt/images
          make package/zerotier/compile
          mv /opt/rt-n56u/bin/targets/mipsel-3.4/generic-glibc/packages/* /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images      
